=== ramadesplats/Internship_Project/GlobalSchema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="RefGlobale">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="etudiants"/>
				<xs:element ref="responsables"/>
				<xs:element ref="stages"/>
				<xs:element ref="entreprises"/>
				<xs:element ref="laboratoires"/>
				<xs:element ref="maitredestages"/>
				<xs:element ref="evalsTechnique"/>
				<xs:element ref="enseignants"/>
				<xs:element ref="jurys"/>
				<xs:element ref="rapports"/>
				<xs:element ref="tuteurs"/>
				<xs:element ref="pos"/>
				<xs:element ref="soutenances"/>
			</xs:sequence>
		</xs:complexType><!-- ###################### KEY ####################### -->
		<xs:key name="keyEtudiant">
			<xs:selector xpath="./etudiants/etudiant"/>
			<xs:field xpath="@idPersonne"/>
		</xs:key>
		<xs:key name="keyResponsable">
			<xs:selector xpath="./responsables/responsable"/>
			<xs:field xpath="@idPersonne"/>
		</xs:key>
		<xs:key name="keyLabo">
			<xs:selector xpath="./laboratoires/laboratoire"/>
			<xs:field xpath="@idEtablissement"/>
		</xs:key>
		<xs:key name="keyEntre">
			<xs:selector xpath="./entreprises/entreprise"/>
			<xs:field xpath="@idEtablissement"/>
		</xs:key>
		<xs:key name="keyEvalTechnique">
			<xs:selector xpath="./evalsTechnique/evaluation"/>
			<xs:field xpath="@idEvalTechnique"/>
		</xs:key>
		<xs:key name="keyMaitredeStage">
			<xs:selector xpath="./maitredestages/maitredestage"/>
			<xs:field xpath="@idMaitredestage"/>
		</xs:key>
		<xs:key name="keyStage">
			<xs:selector xpath="./stages/stage"/>
			<xs:field xpath="@idStage"/>
		</xs:key>
		<xs:key name="keyEnseignant">
			<xs:selector xpath="./enseignants/enseignant"/>
			<xs:field xpath="@idEnseignant"/>
		</xs:key>
		<xs:key name="keyTuteur">
			<xs:selector xpath="./tuteurs/tuteur"/>
			<xs:field xpath="@idTuteur"/>
		</xs:key>
		<xs:key name="keyRapport">
			<xs:selector xpath="./rapports/rapport"/>
			<xs:field xpath="@idRapport"/>
		</xs:key>
		<xs:key name="keyJury">
			<xs:selector xpath="./jurys/jury"/>
			<xs:field xpath="@idJury"/>
		</xs:key>
		<xs:key name="keypo">
			<xs:selector xpath="./pos/po"/>
			<xs:field xpath="@idPo"/>
		</xs:key>
		<xs:key name="keySoutenance">
			<xs:selector xpath="./soutenances/soutenance"/>
			<xs:field xpath="@idSoutenance"/>
		</xs:key><!-- ###################### KEYREF ####################### --><!-- ###################### keyref Stage ####################### -->
		<xs:keyref name="EtudiantdansStage" refer="keyEtudiant">
			<xs:selector xpath="./stages/stage/stagiaire"/>
			<xs:field xpath="@idetudiant"/>
		</xs:keyref>
		<xs:keyref name="refevaltechdestage" refer="keyEvalTechnique">
			<xs:selector xpath="./stages/stage/evaltechnique"/>
			<xs:field xpath="@idevaltech"/>
		</xs:keyref>
		<xs:keyref name="podestage" refer="keypo">
			<xs:selector xpath="./stages/stage/po"/>
			<xs:field xpath="@idpo"/>
		</xs:keyref>
		<xs:keyref name="MaitresdeStageDansStage" refer="keyMaitredeStage">
			<xs:selector xpath="./stages/stage/maitredestage"/>
			<xs:field xpath="@idmaitredestage"/>
		</xs:keyref>
		<xs:keyref name="TuteurdansStage" refer="keyTuteur">
			<xs:selector xpath="./stages/stage/tuteur"/>
			<xs:field xpath="@idtuteur"/>
		</xs:keyref>
		<xs:keyref name="RapportdansStage" refer="keyRapport">
			<xs:selector xpath="./stages/stage/rapport"/>
			<xs:field xpath="@idrapport"/>
		</xs:keyref><!-- ###################### keyref Maitre de stage####################### -->
		<xs:keyref name="ResponsableDansMaitredeStage" refer="keyResponsable">
			<xs:selector xpath="./maitredestages/maitredestage"/>
			<xs:field xpath="@idresponsable"/>
		</xs:keyref><!-- ###################### keyref Evalulation technique####################### -->
		<xs:keyref name="MaitreDansEvalTechnique" refer="keyMaitredeStage">
			<xs:selector xpath="./evalsTechnique/evaluation/maitredestage"/>
			<xs:field xpath="@idmaitredestage"/>
		</xs:keyref><!-- ###################### keyref Enseignant####################### -->
		<xs:keyref name="refEnseignantResp" refer="keyResponsable">
			<xs:selector xpath="./enseignants/enseignant/responsable_enseignant"/>
			<xs:field xpath="@idresponsable"/>
		</xs:keyref><!-- ###################### keyref Jury####################### -->
		<xs:keyref name="EnseignantsduJury" refer="keyEnseignant">
			<xs:selector xpath="./jurys/jury/jury_enseignant"/>
			<xs:field xpath="@idenseignant"/>
		</xs:keyref>
		<xs:keyref name="MaitresDeStageduJury" refer="keyMaitredeStage">
			<xs:selector xpath="./jurys/jury/jury_maitre_de_stage"/>
			<xs:field xpath="@idmaitre_de_stage"/>
		</xs:keyref>
		<xs:keyref name="TuteurduJury" refer="keyTuteur">
			<xs:selector xpath="./jury/jury/jury-tuteur"/>
			<xs:field xpath="@idtuteur"/>
		</xs:keyref><!-- ###################### keyref Rapport####################### -->
		<xs:keyref name="EnseignantRapporteurdansRapport" refer="keyEnseignant">
			<xs:selector xpath="./rapports/rapport/enseignant_rapporteur"/>
			<xs:field xpath="@idenseignant"/>
		</xs:keyref>
		<xs:keyref name="EnseignantsdansRapport" refer="keyEnseignant">
			<xs:selector xpath="./rapports/rapport/enseignants/enseignant"/>
			<xs:field xpath="@idenseignant"/>
		</xs:keyref>
		<xs:keyref name="SoutenanceDansRapport" refer="keySoutenance">
			<xs:selector xpath="./rapports/rapport/soutenance"/>
			<xs:field xpath="@idSoutenance"/>
		</xs:keyref><!-- ###################### keyref Tuteur####################### -->
		<xs:keyref name="EnseignantdansTuteur" refer="keyEnseignant">
			<xs:selector xpath="tuteurs/tuteur/enseignant_tuteur"/>
			<xs:field xpath="@idenseignant"/>
		</xs:keyref><!-- ###################### keyref Soutenance####################### -->
		<xs:keyref name="juryDansSoutenance" refer="keyJury">
			<xs:selector xpath="./soutenances/soutenance/jury"/>
			<xs:field xpath="@idjury"/>
		</xs:keyref><!-- ###################### keyref labo####################### -->
		<xs:keyref name="labodechercheur" refer="keyLabo">
			<xs:selector xpath="./maitredestages/maitredestage/chercheur"/>
			<xs:field xpath="@idLaboratoire"/>
		</xs:keyref><!-- ###################### keyref entreprise####################### -->
		<xs:keyref name="entreprisedeindus" refer="keyEntre">
			<xs:selector xpath="./maitredestages/maitredestage/chercheur"/>
			<xs:field xpath="@idEntrepr"/>
		</xs:keyref>
	</xs:element><!-- ###################### PERSONNE ####################### -->
	<xs:complexType name="personneT">
		<xs:sequence>
			<xs:element name="nom" type="xs:string"/>
			<xs:element name="prenom" type="xs:string"/>
			<xs:element name="date_naissance">
				<xs:simpleType>
					<xs:restriction base="xs:date">
						<xs:minInclusive value="1900-01-01"/>
						<xs:maxInclusive value="2000-01-01"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
		</xs:sequence>
		<xs:attribute name="idPersonne" type="xs:ID" use="required"/>
	</xs:complexType><!-- ###################### ETUDIANT ####################### -->
	<xs:element name="etudiants">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="etudiant" maxOccurs="unbounded" minOccurs="0" type="personneT"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element><!-- ###################### RESPONSABLE ####################### -->
	<xs:complexType name="responsableT">
		<xs:complexContent>
			<xs:extension base="personneT">
				<xs:sequence>
					<xs:element name="fonction" type="xs:string"/>
					<xs:element name="telephone">
						<xs:simpleType>
							<xs:restriction base="xs:string">
								<xs:pattern value="0[1-8][0-9]{8}"/>
							</xs:restriction>
						</xs:simpleType>
					</xs:element>
					<xs:element name="email" type="xs:string"/>
				</xs:sequence>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:element name="responsables">
		<xs:complexType>
			<xs:sequence>
				<xs:element maxOccurs="unbounded" minOccurs="0" name="responsable" type="responsableT"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element><!-- ###################### STAGE ####################### -->
	<xs:complexType name="stageT">
		<xs:sequence>
			<xs:element name="intitule" type="xs:string"/>
			<xs:element maxOccurs="unbounded" minOccurs="1" name="motClef" type="xs:string"/>
			<xs:element name="duree" type="xs:integer"/><!-- Fixer une convention pour la durÃ©e (en mois, en jours, etc.) -->
			<xs:element name="annee">
				<xs:simpleType>
					<xs:restriction base="xs:integer">
						<xs:minInclusive value="1850"/>
						<xs:maxInclusive value="2016"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
			<xs:element name="po">
				<xs:complexType>
					<xs:attribute name="idpo" type="xs:token" use="required"/>
				</xs:complexType>
			</xs:element>
			<xs:element name="evaltechnique">
				<xs:complexType>
					<xs:attribute name="idevaltech" type="xs:token" use="required"/>
				</xs:complexType>
			</xs:element>
			<xs:element name="stagiaire">
				<xs:complexType>
					<xs:attribute name="idetudiant" type="xs:token" use="required"/>
				</xs:complexType>
			</xs:element>
			<xs:element name="tuteur">
				<xs:complexType>
					<xs:attribute name="idtuteur" type="xs:token" use="required"/>
				</xs:complexType>
			</xs:element>
			<xs:element name="maitredestage" minOccurs="0" maxOccurs="unbounded">
				<xs:complexType>
					<xs:attribute name="idmaitredestage" type="xs:token" use="required"/>
				</xs:complexType>
			</xs:element>
			<xs:element name="rapport">
				<xs:complexType>
					<xs:attribute name="idrapport" type="xs:token" use="required"/>
				</xs:complexType>
			</xs:element>
		</xs:sequence>
		<xs:attribute name="idStage" type="xs:ID" use="required"/>
	</xs:complexType>
	<xs:element name="stages">
		<xs:complexType>
			<xs:sequence>
				<xs:element maxOccurs="unbounded" minOccurs="0" name="stage" type="stageT"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element><!-- ###################### ETABLISSEMENT ####################### -->
	<xs:complexType name="etalissementT">
		<xs:sequence>
			<xs:element name="nom" type="xs:string"/>
			<xs:element name="adresse" type="xs:string"/>
		</xs:sequence>
		<xs:attribute name="idEtablissement" type="xs:ID" use="required"/>
	</xs:complexType>
	<xs:complexType name="laboT">
		<xs:complexContent>
			<xs:extension base="etalissementT">
				<xs:sequence>
					<xs:element name="unite" type="xs:string"/>
				</xs:sequence>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="entrepriseT">
		<xs:complexContent>
			<xs:extension base="etalissementT">
				<xs:sequence>
					<xs:element name="siret" type="xs:string"/>
				</xs:sequence>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:element name="entreprises">
		<xs:complexType>
			<xs:sequence>
				<xs:element maxOccurs="unbounded" minOccurs="0" name="entreprise" type="entrepriseT"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="laboratoires">
		<xs:complexType>
			<xs:sequence>
				<xs:element maxOccurs="unbounded" minOccurs="0" name="laboratoire" type="laboT"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element><!-- ###################### MAITRE DE STAGE ####################### -->
	<xs:complexType name="maitredestageT">
		<xs:choice>
			<xs:element name="industriel" type="industrielT"/>
			<xs:element name="chercheur" type="chercheurT"/>
		</xs:choice>
		<xs:attribute name="idMaitredestage" use="required" type="xs:ID"/>
		<xs:attribute name="idresponsable" type="xs:token" use="required"/>
	</xs:complexType>
	<xs:complexType name="chercheurT">
		<xs:attribute name="idLaboratoire" type="xs:token"/>
	</xs:complexType>
	<xs:complexType name="industrielT">
		<xs:attribute name="idEntrepr" type="xs:token"/>
	</xs:complexType>
	<xs:element name="maitredestages">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="maitredestage" type="maitredestageT" minOccurs="0" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element><!-- ###################### EVALUATION TECHNIQUE ####################### -->
	<xs:complexType name="evalTechniqueT">
		<xs:sequence>
			<xs:element name="commIntegration" type="xs:string"/>
			<xs:element name="commTechnique" type="xs:string"/>
			<xs:element name="commCommunication" type="xs:string"/>
			<xs:element name="note" type="xs:integer"/>
			<xs:element name="maitredestage">
				<xs:complexType>
					<xs:attribute name="idmaitredestage" type="xs:token" use="required"/>
				</xs:complexType>
			</xs:element>
		</xs:sequence>
		<xs:attribute name="idEvalTechnique" use="required" type="xs:ID"/>
	</xs:complexType>
	<xs:element name="evalsTechnique">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="evaluation" type="evalTechniqueT" minOccurs="0" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element><!-- ###################### ENSEIGNANT ####################### -->
	<xs:complexType name="enseignantT">
		<xs:sequence>
			<xs:element name="responsable_enseignant">
				<xs:complexType>
					<xs:attribute name="idresponsable" type="xs:token" use="required"/>
				</xs:complexType>
			</xs:element>
		</xs:sequence>
		<xs:attribute name="idEnseignant" use="required" type="xs:ID"/>
	</xs:complexType>
	<xs:element name="enseignants">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="enseignant" type="enseignantT" minOccurs="0" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element><!-- ###################### JURY ####################### -->
	<xs:complexType name="juryT">
		<xs:sequence>
			<xs:element name="jury_enseignant" minOccurs="1" maxOccurs="5">
				<xs:complexType>
					<xs:attribute name="idenseignant" type="xs:token" use="required"/>
				</xs:complexType>
			</xs:element>
			<xs:element name="jury_maitre_de_stage" minOccurs="1" maxOccurs="5">
				<xs:complexType>
					<xs:attribute name="idmaitre_de_stage" type="xs:token" use="required"/>
				</xs:complexType>
			</xs:element>
			<xs:element name="jury_tuteur">
				<xs:complexType>
					<xs:attribute name="idtuteur" type="xs:token" use="required"/>
				</xs:complexType>
			</xs:element>
		</xs:sequence>
		<xs:attribute name="idJury" use="required" type="xs:ID"/>
	</xs:complexType>
	<xs:element name="jurys">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="jury" type="juryT"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element><!-- ###################### RAPPORT ####################### -->
	<xs:complexType name="enseignantsRapportT">
		<xs:sequence>
			<xs:element name="enseignant" minOccurs="0" maxOccurs="unbounded">
				<xs:complexType>
					<xs:attribute name="idenseignant" type="xs:token" use="required"/>
				</xs:complexType>
			</xs:element>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="rapportT">
		<xs:sequence>
			<xs:element name="intitule" type="xs:string"/>
			<xs:element name="note_rapporteur" type="xs:string"/>
			<xs:element name="note_jury" type="xs:string"/>
			<xs:element name="enseignant_rapporteur">
				<xs:complexType>
					<xs:attribute name="idenseignant" type="xs:token" use="required"/>
				</xs:complexType>
			</xs:element>
			<xs:element name="enseignants" type="enseignantsRapportT" minOccurs="1" maxOccurs="5"/>
			<xs:element name="soutenance" minOccurs="0">
				<xs:complexType>
					<xs:attribute name="idSoutenance" type="xs:token" use="required"/>
				</xs:complexType>
			</xs:element>
		</xs:sequence>
		<xs:attribute name="idRapport" use="required" type="xs:ID"/>
	</xs:complexType>
	<xs:element name="rapports">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="rapport" type="rapportT" minOccurs="0" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element><!-- ###################### TUTEUR ####################### -->
	<xs:complexType name="tuteurT">
		<xs:sequence>
			<xs:element name="enseignant_tuteur">
				<xs:complexType>
					<xs:attribute name="idenseignant" type="xs:token" use="required"/>
				</xs:complexType>
			</xs:element>
		</xs:sequence>
		<xs:attribute name="idTuteur" use="required" type="xs:ID"/>
	</xs:complexType>
	<xs:element name="tuteurs">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="tuteur" type="tuteurT" minOccurs="0" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element><!-- ###################### PO ####################### -->
	<xs:complexType name="poT">
		<xs:sequence>
			<xs:element name="intitule" type="xs:string"/>
			<xs:element name="departement" type="xs:string"/>
		</xs:sequence>
		<xs:attribute name="idPo" use="required" type="xs:ID"/>
	</xs:complexType>
	<xs:element name="pos">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="po" type="poT" minOccurs="0" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element><!-- ###################### SOUTENANCE ####################### -->
	<xs:complexType name="soutenanceT">
		<xs:sequence>
			<xs:element name="date">
				<xs:simpleType>
					<xs:restriction base="xs:date">
						<xs:minInclusive value="2000-01-01"/>
						<xs:maxInclusive value="2025-01-01"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
			<xs:element name="lieu" type="xs:string"/>
			<xs:element name="note_soutenance" type="xs:integer"/>
			<xs:element name="jury">
				<xs:complexType>
					<xs:attribute name="idjury" type="xs:token" use="required"/>
				</xs:complexType>
			</xs:element>
		</xs:sequence>
		<xs:attribute name="idSoutenance" use="required" type="xs:ID"/>
	</xs:complexType>
	<xs:element name="soutenances">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="soutenance" type="soutenanceT" minOccurs="0" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== ramadesplats/Internship_Project/GlobalXML.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xslt" href="GlobalXSLT.xslt"?>
<RefGlobale xsi:noNamespaceSchemaLocation="/Users/Guillaume/Desktop/GlobalSchema.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
	<etudiants>
		<etudiant idPersonne="idPersonne-1">
			<nom>DE BRITO</nom>
			<prenom>Guilaume</prenom>
			<date_naissance>1995-05-02</date_naissance>
		</etudiant>
		<etudiant idPersonne="idPersonne-2">
			<nom>CHABERT</nom>
			<prenom>Paul</prenom>
			<date_naissance>1995-12-02</date_naissance>
		</etudiant>
		<etudiant idPersonne="idPersonne-3">
			<nom>DESPLATS</nom>
			<prenom>Rama</prenom>
			<date_naissance>1995-01-01</date_naissance>
		</etudiant>
	</etudiants>
	<responsables>
		<responsable idPersonne="idPersonne-4">
			<nom>DUMEDON</nom>
			<prenom>Fabrice</prenom>
			<date_naissance>1985-02-03</date_naissance>
			<fonction>Directeur de la recherche chez Pierre Fabre</fonction>
			<telephone>0673935746</telephone>
			<email>dumedon@pierrefabre.com</email>
		</responsable>
		<responsable idPersonne="idPersonne-5">
			<nom>PONCETTE</nom>
			<prenom>Mathilde</prenom>
			<date_naissance>1970-02-12</date_naissance>
			<fonction>Chef de projet chez AppDev</fonction>
			<telephone>0649284028</telephone>
			<email>m.poncette@appdev.fr</email>
		</responsable>
		<responsable idPersonne="idPersonne-6">
			<nom>MACHIT</nom>
			<prenom>Julien</prenom>
			<date_naissance>1975-12-02</date_naissance>
			<fonction>Ingénieur chez Pub4life</fonction>
			<telephone>0789482743</telephone>
			<email>machit.julien@pubforlife.com</email>
		</responsable>
		<responsable idPersonne="idPersonne-7">
			<nom>HIBRA</nom>
			<prenom>Enzo</prenom>
			<date_naissance>1985-02-01</date_naissance>
			<fonction>Professeur à l'INSA Toulouse - GB</fonction>
			<telephone>0763543939</telephone>
			<email>hibra@insa-toulouse.fr</email>
		</responsable>
		<responsable idPersonne="idPersonne-8">
			<nom>THAUVE</nom>
			<prenom>Gerard</prenom>
			<date_naissance>1965-10-02</date_naissance>
			<fonction>Professeur à l'INSA Toulouse - GEI</fonction>
			<telephone>0768899008</telephone>
			<email>thauve@insa-toulouse.fr</email>
		</responsable>
		<responsable idPersonne="idPersonne-9">
			<nom>ALEXANDRE</nom>
			<prenom>Romain</prenom>
			<date_naissance>1990-07-08</date_naissance>
			<fonction>Professeur à l'INSA Toulouse - GEI</fonction>
			<telephone>0973829273</telephone>
			<email>alexandre@insa-toulouse.fr</email>
		</responsable>
		<responsable idPersonne="idPersonne-10">
			<nom>PUJOL</nom>
			<prenom>Anais</prenom>
			<date_naissance>1980-11-11</date_naissance>
			<fonction>Professeur à l'INSA Toulouse - GB</fonction>
			<telephone>0763638392</telephone>
			<email>pujol@insa-toulouse.fr</email>
		</responsable>
		<responsable idPersonne="idPersonne-11">
			<nom>TRULE</nom>
			<prenom>Jean</prenom>
			<date_naissance>1975-01-10</date_naissance>
			<fonction>Sous chef de projet chez AppDev</fonction>
			<telephone>0649724027</telephone>
			<email>j.trule@appdev.fr</email>
		</responsable>
	</responsables>
	<stages>
        <stage idStage="ID-1">
            <intitule>Developpement d'une molécule</intitule>
            <motClef>Création d'une molécule qui guérit la grippe</motClef>
            <duree>6</duree>
            <annee>2014</annee>
            <po idpo="idPo-1"/>
            <evaltechnique idevaltech="Id_Eval_1"/>
            <stagiaire idetudiant="idPersonne-1"/>
            <tuteur idtuteur="Id_Tut_1"/>
            <maitredestage idmaitredestage="idMaitre-1"/>
            <rapport idrapport="Id_Rap_1"/>
        </stage>
		<stage idStage="ID-2">
			<intitule>Application android </intitule>
			<motClef>Création d'un sudoku sur android</motClef>
			<duree>3</duree>
			<annee>2015</annee>
			<po idpo="idPo-2"/>
			<evaltechnique idevaltech="Id_Eval_2"/>
			<stagiaire idetudiant="idPersonne-2"/>
			<tuteur idtuteur="Id_Tut_2"/>
			<maitredestage idmaitredestage="idMaitre-2"/>
			<maitredestage idmaitredestage="idMaitre-4"/>
			<rapport idrapport="Id_Rap_2"/>
		</stage>
		<stage idStage="ID-3">
			<intitule>Code Ocaml pour publicité</intitule>
			<motClef>Création de bandeaux publicitaire pour site internet</motClef>
			<duree>3</duree>
			<annee>2016</annee>
			<po idpo="idPo-2"/>
			<evaltechnique idevaltech="Id_Eval_3"/>
			<stagiaire idetudiant="idPersonne-3"/>
			<tuteur idtuteur="Id_Tut_3"/>
			<maitredestage idmaitredestage="idMaitre-3"/>
			<rapport idrapport="Id_Rap_3"/>
		</stage>
	</stages>
	<entreprises>
		<entreprise idEtablissement="idEntre-3">
			<nom>Pub4life</nom>
			<adresse>10 rue du petit pommier 22400 Dumois</adresse>
			<siret>16516</siret>
		</entreprise>
		<entreprise idEtablissement="idEntre-4">
			<nom>AppDev</nom>
			<adresse>30 avenue de la Marnet</adresse>
			<siret>58454</siret>
		</entreprise>
	</entreprises>
	<laboratoires>
		<laboratoire idEtablissement="idEntre-1">
			<nom>Pierre fabre</nom>
			<adresse>15 avenue du pin penché 31100 Toulouse</adresse>
			<unite>Medicament</unite>
		</laboratoire>
		<laboratoire idEtablissement="idEntre-2">
			<nom>Bayer</nom>
			<adresse>5 rue du colonnel Vigilant 83100 Toulon</adresse>
			<unite>Vaccin</unite>
		</laboratoire>
	</laboratoires>
	<maitredestages>
		<maitredestage idMaitredestage="idMaitre-1" idresponsable="idPersonne-4">
			<chercheur idLaboratoire="idEntre-1"/>
		</maitredestage>
		<maitredestage idMaitredestage="idMaitre-2" idresponsable="idPersonne-5">
			<industriel idEntrepr="idEntre-4"/>
		</maitredestage>
		<maitredestage idMaitredestage="idMaitre-3" idresponsable="idPersonne-6">
			<industriel idEntrepr="idEntre-3"/>
		</maitredestage>
		<maitredestage idMaitredestage="idMaitre-4" idresponsable="idPersonne-11">
			<industriel idEntrepr="idEntre-4"/>
		</maitredestage>
	</maitredestages>
	<evalsTechnique>
		<evaluation idEvalTechnique="Id_Eval_1">
			<commIntegration>S'est bien intégré</commIntegration>
			<commTechnique>Bon bagage technique</commTechnique>
			<commCommunication>S'est vite adapté à l'équipe</commCommunication>
			<note>1</note>
			<maitredestage idmaitredestage="idMaitre-1"/>
		</evaluation>
		<evaluation idEvalTechnique="Id_Eval_2">
			<commIntegration>Des débuts difficiles</commIntegration>
			<commTechnique>Fort en programmation</commTechnique>
			<commCommunication>Parle peu</commCommunication>
			<note>12</note>
			<maitredestage idmaitredestage="idMaitre-2"/>
			<maitredestage idmaitredestage="idMaitre-4"/>
		</evaluation>
		<evaluation idEvalTechnique="Id_Eval_3">
			<commIntegration>Rien à dire</commIntegration>
			<commTechnique>Des progrès à faire en XML</commTechnique>
			<commCommunication>Communication excellente</commCommunication>
			<note>16</note>
			<maitredestage idmaitredestage="idMaitre-3"/>
		</evaluation>
	</evalsTechnique>
	<enseignants>
		<enseignant idEnseignant="Id_Ens_1">
			<responsable_enseignant idresponsable="idPersonne-7"/>
		</enseignant>
		<enseignant idEnseignant="Id_Ens_2">
			<responsable_enseignant idresponsable="idPersonne-8"/>
		</enseignant>
		<enseignant idEnseignant="Id_Ens_3">
			<responsable_enseignant idresponsable="idPersonne-9"/>
		</enseignant>
		<enseignant idEnseignant="Id_Ens_4">
			<responsable_enseignant idresponsable="idPersonne-10"/>
		</enseignant>
	</enseignants>
	<jurys>
		<jury idJury="Id_Jur_1">
			<jury_enseignant idenseignant="Id_Ens_1"/>
			<jury_enseignant idenseignant="Id_Ens_4"/>
			<jury_maitre_de_stage idmaitre_de_stage="idMaitre-1"/>
			<jury_tuteur idtuteur="Id_Tut_1"/>
		</jury>
		<jury idJury="Id_Jur_2">
			<jury_enseignant idenseignant="Id_Ens_2"/>
			<jury_enseignant idenseignant="Id_Ens_3"/>
			<jury_maitre_de_stage idmaitre_de_stage="idMaitre-2"/>
			<jury_maitre_de_stage idmaitre_de_stage="idMaitre-4"/>
			<jury_tuteur idtuteur="Id_Tut_2"/>
		</jury>
		<jury idJury="Id_Jur_3">
			<jury_enseignant idenseignant="Id_Ens_2"/>
			<jury_enseignant idenseignant="Id_Ens_3"/>
			<jury_maitre_de_stage idmaitre_de_stage="idMaitre-3"/>
			<jury_tuteur idtuteur="Id_Tut_3"/>
		</jury>
	</jurys>
	<rapports>
		<rapport idRapport="Id_Rap_1">
			<intitule>Rapport de GUILLAUME DE BRITO</intitule>
			<note_rapporteur>2</note_rapporteur>
			<note_jury>13</note_jury>
			<enseignant_rapporteur idenseignant="Id_Ens_1"/>
			<enseignants>
				<enseignant idenseignant="Id_Ens_1"/>
				<enseignant idenseignant="Id_Ens_4"/>
			</enseignants>
			<soutenance idSoutenance="Id_Sou_1"/>
		</rapport>
		<rapport idRapport="Id_Rap_2">
			<intitule>Rapport de PAUL CHABERT</intitule>
			<note_rapporteur>20</note_rapporteur>
			<note_jury>19</note_jury>
			<enseignant_rapporteur idenseignant="Id_Ens_2"/>
			<enseignants>
				<enseignant idenseignant="Id_Ens_2"/>
			</enseignants>
			<soutenance idSoutenance="Id_Sou_2"/>
		</rapport>
		<rapport idRapport="Id_Rap_3">
			<intitule>Rapport de RAMA DESPLATS</intitule>
			<note_rapporteur>18</note_rapporteur>
			<note_jury>20</note_jury>
			<enseignant_rapporteur idenseignant="Id_Ens_3"/>
			<enseignants>
				<enseignant idenseignant="Id_Ens_2"/>
				<enseignant idenseignant="Id_Ens_3"/>
			</enseignants><!--Pour Xquery
			<soutenance idSoutenance="Id_Sou_3"/-->
		</rapport>
	</rapports>
	<tuteurs>
		<tuteur idTuteur="Id_Tut_1">
			<enseignant_tuteur idenseignant="Id_Ens_1"/>
		</tuteur>
		<tuteur idTuteur="Id_Tut_2">
			<enseignant_tuteur idenseignant="Id_Ens_2"/>
		</tuteur>
		<tuteur idTuteur="Id_Tut_3">
			<enseignant_tuteur idenseignant="Id_Ens_3"/>
		</tuteur>
	</tuteurs>
	<pos>
		<po idPo="idPo-1">
			<intitule>ICBE</intitule>
			<departement>GB</departement>
		</po>
		<po idPo="idPo-2">
			<intitule>MIC</intitule>
			<departement>GEI</departement>
		</po>
	</pos>
	<soutenances>
		<soutenance idSoutenance="Id_Sou_1">
			<date>2014-02-02</date>
			<lieu>Toulouse</lieu>
			<note_soutenance>18</note_soutenance>
			<jury idjury="Id_Jur_1"/>
		</soutenance>
		<soutenance idSoutenance="Id_Sou_2">
			<date>2015-12-12</date>
			<lieu>Toulouse</lieu>
			<note_soutenance>1</note_soutenance>
